version: '3.9'

services:
  gateway:
    image: nginx:latest
    container_name: nft-api-gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/localhost.pem/:/etc/nginx/ssl/subdomain.rarebay.ru
      - ./ssl/localhost.key/:/etc/nginx/ssl/subdomain.rarebay.key
    depends_on:
      - main_service
      - content_service
    networks:
      - public

  main_service:
    env_file: "../main_service/.env"
    image: ton-nft-main-service:latest
    container_name: nft-main-service
    build:
      context: ../main_service
      dockerfile: ../main_service/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis_main_db
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    networks:
      - main_network
      - private
      - public
  
  content_service:
    env_file: "../content_service/.env"
    image: ton-nft-content-service:latest
    container_name: nft-content-service
    build:
      context: ../content_service
      dockerfile: ../content_service/Dockerfile
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_USER_PASSWORD=${MONGO_DB_USER_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mongo_content_db
    networks:
      - content_network
      - private
      - public

  redis_main_db:
    image: redis:latest
    container_name: redis-container
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-main-data:/var/lib/redis-data
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "appendonly yes" >> /usr/local/etc/redis/redis.conf &&
        echo "appendfsync everysec" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $REDIS_USER on >$REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - main_network
  
  mongo_content_db:
    image: mongo:latest
    container_name: mongo-content-service-db
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo-content-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_USER_PASSWORD}
    networks:
      - content_network

volumes:
  redis-main-data:
  mongo-content-data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
  content_network:
    driver: bridge
  main_network:
    driver: bridge