name: Dev CI/CD
on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  test_build_job:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build main-service container
        run: |
          docker build -t nft-main-service-image ./main_service
      
      - name: Run main-service container
        run: |
          docker run --rm --name nft-main-service -d nft-main-service-image
          sleep 10
          docker logs nft-main-service
          docker ps | grep nft-main-service
          docker stop nft-main-service
      
      - name: Build content-service container
        run: |
          docker build -t content-service-image ./content_service
      
      - name: Run content-service container
        run: |
          docker run -e TON_API_KEY="TON_API_KEY" \
          -e MONGO_HOST="MONGO_HOST" \
          -e MONGO_DB_NAME="MONGO_DB_NAME" \
          -e IS_TESTNET=True \
          --rm -d --name nft-content-service content-service-image
          sleep 10
          docker logs nft-content-service
          docker ps | grep nft-content-service
          docker stop nft-content-service
  
  deploy_dev_job:
    needs: test_build_job
    name: Deploy to Development server
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Connect to server
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            cd projects/nft-backend/
            git checkout dev
            git pull
            cd docker/
            docker-compose up -d --build


