name: Dev CI/CD
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test_build_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@4
      - name: Set up Python 3.12
        uses: actions/setup-python
        with:
          python-version: '3.12'
      
      - name: Build Docker container
        run: |
          docker build -t nft-backend-image .
      
      - name: Run Docker container
        run: |
          docker run --rm nft-backend-image -d
          sleep 5
          docker logs nft-backend-image
          docker ps | grep nft-backend-image