name: Dev CI/CD
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  test_build_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker container
        run: |
          docker build -t nft-backend-image .
      
      - name: Run Docker container
        run: |
          docker run --rm --name nft-backend -d nft-backend-image
          sleep 5
          docker logs nft-backend
          docker ps | grep nft-backend